// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkgWqvNAvwKl34L_Nipb3o5OWnPXYW6NA',
    appId: '1:843308831272:web:f0582f186d8ba051afdb1d',
    messagingSenderId: '843308831272',
    projectId: 'imaginescholar-8cd51',
    authDomain: 'imaginescholar-8cd51.firebaseapp.com',
    databaseURL: 'https://imaginescholar-8cd51-default-rtdb.firebaseio.com',
    storageBucket: 'imaginescholar-8cd51.appspot.com',
    measurementId: 'G-9YL9CRCN3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-wkbhsSMLUXepj3Ie1zh3XkeEwJ9Fzo',
    appId: '1:843308831272:android:ed9a9b5e703f4fb9afdb1d',
    messagingSenderId: '843308831272',
    projectId: 'imaginescholar-8cd51',
    databaseURL: 'https://imaginescholar-8cd51-default-rtdb.firebaseio.com',
    storageBucket: 'imaginescholar-8cd51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMw2_w4CFPcMNi7_aTOjMx_P3e6IqyCOQ',
    appId: '1:843308831272:ios:fdb110f5b07a04deafdb1d',
    messagingSenderId: '843308831272',
    projectId: 'imaginescholar-8cd51',
    databaseURL: 'https://imaginescholar-8cd51-default-rtdb.firebaseio.com',
    storageBucket: 'imaginescholar-8cd51.appspot.com',
    iosClientId: '843308831272-dgq8b5gj263adgomgu3iedvrj4elm0i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.imaginineScholar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMw2_w4CFPcMNi7_aTOjMx_P3e6IqyCOQ',
    appId: '1:843308831272:ios:ad4fb012de3781deafdb1d',
    messagingSenderId: '843308831272',
    projectId: 'imaginescholar-8cd51',
    databaseURL: 'https://imaginescholar-8cd51-default-rtdb.firebaseio.com',
    storageBucket: 'imaginescholar-8cd51.appspot.com',
    iosClientId: '843308831272-hk6mkra9gq0tuc088lrd9o0i8gf01skl.apps.googleusercontent.com',
    iosBundleId: 'com.example.imaginineScholar.RunnerTests',
  );
}
